### ISSUE TITLE
Native and Web clients render avatars at differing elevations

### ISSUE THREAD

**Issue by ctrlaltdavid** [vircadia/vircadia-web#126]
![image](https://user-images.githubusercontent.com/7455448/216517817-37376352-6cd9-44a8-8675-a113ae1aff0d.png)

**Comment by scatterp2** [comment]
i think this may not be a bug but i am not sure what i suspect is happening is the native viewer takes in to account the offset of the 3d object while the web viewer correctly calculates the center of the object and places it 
take this as a clue not facts.. because i am far from clear on what's happening currently...
